baseURL = "https://dombraccia.github.io/"
publishDir = "dombraccia.github.io"
languageCode = "en-us"
title = "personal site for Domenick J. Braccia"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2 

[params]
  google_analytics_id=""
  homepage_button_link = '/blog'
  homepage_button_text = 'Latest Posts'
  homepage_intro = 'My personal site. See links to my contact information, projects, and a few blog posts.'
  homepage_image = ''

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "[description]"
    meta_og_title = "personal site"
    meta_og_type = "website"
    meta_og_url = "https://dombraccia.github.io"
    meta_og_image = "path/to/image/of/me"
    meta_og_description = "personal site"
    meta_twitter_card = "summary"
    meta_twitter_site = "@dombraccia"
    meta_twitter_creator = "@dombraccia"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
